### ISSUE TITLE
Problem with chat updates when creating a lobby

### ISSUE THREAD

**Issue by Sigma-dev** [QueenOfSquiggles/bevy_steamworks#1]
I'd like to preface this by saying I appreciate your work for this otherwise forgotten crate. This is my last resort to find a fix for my issue as I can't really find anything resembling a community for this.

```rust
use bevy::prelude::*;
use bevy_steamworks::{self, Client, LobbyType, SteamworksEvent, SteamworksPlugin};

fn steam_system(
    steam_client: Res<Client>,
    keys: Res<ButtonInput<KeyCode>>,
) {
    if keys.just_pressed(KeyCode::KeyC) {
        steam_client.matchmaking().create_lobby(
            LobbyType::FriendsOnly,
            2,
            |r| { 
                match r {
                    Ok(lobby_id) => println!("YES: {}", lobby_id.raw()),
                    Err(e) => println!("NO: {}", e),
                }
            });
        return;
    }
}

fn steam_events(
    mut evs: EventReader<SteamworksEvent>,
) {
    for ev in evs.read() {
        println!("Event received");
        match ev {
            SteamworksEvent::LobbyChatUpdate(info) => {
                println!("Chat Update");
                match info.member_state_change {
                    bevy_steamworks::ChatMemberStateChange::Entered => println!("ENTERED"),
                    _ => println!("Non-entered chat update")
                }
            },
            _ => println!("Non chat update event received"),
        }
    }
}

fn main() {
    App::new()
        .add_plugins(SteamworksPlugin::init_app(480).unwrap())
        .add_plugins(DefaultPlugins)
        .add_systems(Update, (steam_system, steam_events))
        .run();
}
```

From the steamworks docs, when a user creates a lobby, they should receive a lobbychatupdate saying they entered.
But when in this example code I succesfully create a lobby (the callback is positive), I do not get the lobbychatupdate.

I am not sure if this is an internal issue or what but I couldn't figure it out sadly, hope you or someone else can help me out.
Thanks again for your contribution regardsless

**Comment by Sigma-dev** [comment]
Upon further examination, it seems that it could be how the API is supposed to work. I'm not sure.

**Comment by QueenOfSquiggles** [comment]
I'll be honest. I haven't devoted a whole lot of time towards learning the steamworks API yet. My goal was to develop my understanding as I worked on my own game with this. Since `steamworks-rs` is just a bindgen on the C++ SDK, I would assume any community references and guides should be valid. I'd recommend checking the docs and any useful guides to see if that helps clarify the flow of events. 

I am going to close this issue since there isn't really anything actionable that I can do about this. Best of luck though!
